default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>

development:
  <<: *default
  database: auth_development

test:
  <<: *default
  database: auth_test

production:
  <<: *default
  database: auth_production
  username: auth
  password: <%= ENV['AUTH_DATABASE_PASSWORD'] %>